# Generated by Django 5.0.1 on 2024-02-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aunthentification', '0003_class1_class10_class7_class8_class9'),
    ]

    operations = [
        migrations.DeleteModel(
            name='class1',
        ),
    ]
