# Generated by Django 5.0.1 on 2024-02-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aunthentification', '0004_delete_class1'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjectMaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousQuestion', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=100)),
                ('newQuestion', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='subjectScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousQuestion', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=100)),
                ('newQuestion', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='subjectSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousQuestion', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=100)),
                ('newQuestion', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='subjectTelugu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousQuestion', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=100)),
                ('newQuestion', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
