# Generated by Django 5.0.1 on 2024-02-26 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aunthentification', '0005_subjectmaths_subjectscience_subjectsocial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='class77',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('subjectMath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aunthentification.subjectmaths')),
                ('subjectScienc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aunthentification.subjectscience')),
                ('subjectSocia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aunthentification.subjectsocial')),
                ('subjectTelug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aunthentification.subjecttelugu')),
            ],
        ),
        migrations.DeleteModel(
            name='class7',
        ),
    ]
