# Generated by Django 5.0.1 on 2024-02-26 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aunthentification', '0006_class77_delete_class7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class77',
            name='subjectMath',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aunthentification.subjectmaths'),
        ),
        migrations.AlterField(
            model_name='class77',
            name='subjectScienc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aunthentification.subjectscience'),
        ),
        migrations.AlterField(
            model_name='class77',
            name='subjectSocia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aunthentification.subjectsocial'),
        ),
        migrations.AlterField(
            model_name='class77',
            name='subjectTelug',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aunthentification.subjecttelugu'),
        ),
    ]
