# Generated by Django 5.0.1 on 2024-02-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aunthentification', '0007_alter_class77_subjectmath_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class77',
            name='subjectMath',
        ),
        migrations.RemoveField(
            model_name='class77',
            name='subjectScienc',
        ),
        migrations.RemoveField(
            model_name='class77',
            name='subjectSocia',
        ),
        migrations.RemoveField(
            model_name='class77',
            name='subjectTelug',
        ),
    ]
