# Generated by Django 5.0.1 on 2024-02-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aunthentification', '0008_remove_class77_subjectmath_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='class77',
            new_name='class7',
        ),
    ]
