# Generated by Django 5.0.1 on 2024-02-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aunthentification', '0009_rename_class77_class7'),
    ]

    operations = [
        migrations.DeleteModel(
            name='class10',
        ),
        migrations.DeleteModel(
            name='class7',
        ),
        migrations.DeleteModel(
            name='class8',
        ),
        migrations.DeleteModel(
            name='class9',
        ),
        migrations.DeleteModel(
            name='subjectMaths',
        ),
        migrations.DeleteModel(
            name='subjectScience',
        ),
        migrations.DeleteModel(
            name='subjectSocial',
        ),
        migrations.DeleteModel(
            name='subjectTelugu',
        ),
    ]
