# Generated by Django 5.0.1 on 2024-02-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aunthentification', '0011_class10_class7_class8_class9'),
    ]

    operations = [
        migrations.CreateModel(
            name='class10Maths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pq', models.CharField(max_length=210)),
                ('answer', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('nq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='class10science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pq', models.CharField(max_length=210)),
                ('answer', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('nq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='class10Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pq', models.CharField(max_length=210)),
                ('answer', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('nq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='class10Telugu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pq', models.CharField(max_length=210)),
                ('answer', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('nq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='class7Maths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pq', models.CharField(max_length=210)),
                ('answer', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('nq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='class7science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pq', models.CharField(max_length=210)),
                ('answer', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('nq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='class7Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pq', models.CharField(max_length=210)),
                ('answer', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('nq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='class7Telugu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pq', models.CharField(max_length=210)),
                ('answer', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('nq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='class8Maths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pq', models.CharField(max_length=210)),
                ('answer', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('nq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='class8science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pq', models.CharField(max_length=210)),
                ('answer', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('nq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='class8Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pq', models.CharField(max_length=210)),
                ('answer', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('nq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='class8Telugu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pq', models.CharField(max_length=210)),
                ('answer', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('nq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='class9Maths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pq', models.CharField(max_length=210)),
                ('answer', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('nq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='class9science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pq', models.CharField(max_length=210)),
                ('answer', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('nq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='class9Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pq', models.CharField(max_length=210)),
                ('answer', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('nq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='class9Telugu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pq', models.CharField(max_length=210)),
                ('answer', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('nq', models.CharField(max_length=200)),
            ],
        ),
    ]
